<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace"
    nsURI="http://www.kermeta.org/SintaksTrace" nsPrefix="trace">
  <eClassifiers xsi:type="ecore:EClass" name="TraceModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" ordered="false"
        eType="#//Trace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceReference" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetReference" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleReference" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTraces" ordered="false"
        upperBound="-1" eType="#//Trace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextReference" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineBeginAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charBeginAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineEndAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charEndAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelReference" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refObject" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="IN_PROGRESS"/>
    <eLiterals name="OK" value="1"/>
    <eLiterals name="FAILURE" value="2"/>
    <eLiterals name="CANCELED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileReference" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
