<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tinyjava"
    nsURI="http://www.ensisa.uha.fr/hassenforder/tinyjava.ecore" nsPrefix="tinyjava">
  <eClassifiers xsi:type="ecore:EClass" name="TJPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//TJClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TJClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caccess" eType="#//TJAccess"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//TJFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TJFeature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="member" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//TJAccess"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ftype" eType="#//TJType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TJData" eSuperTypes="#//TJFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="TJMethod" eSuperTypes="#//TJFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//TJParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TJParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TJType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TJType">
    <eLiterals name="void"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="Character" value="2"/>
    <eLiterals name="Integer" value="3"/>
    <eLiterals name="Real" value="4"/>
    <eLiterals name="String" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TJAccess">
    <eLiterals name="default"/>
    <eLiterals name="public" value="1"/>
    <eLiterals name="protected" value="2"/>
    <eLiterals name="private" value="3"/>
  </eClassifiers>
</ecore:EPackage>
