<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stsgen"
    nsURI="http://www.kermeta.org/SintaksGenModel" nsPrefix="stsgen">
  <eClassifiers xsi:type="ecore:EClass" name="StsGenRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="genClasses" upperBound="-1"
        eType="#//StsGenClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootPackage" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StsGenClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notUsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="false"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classTarget" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genFeatures" upperBound="-1"
        eType="#//StsGenFeature" containment="true" eOpposite="#//StsGenFeature/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genSubClasses" upperBound="-1"
        eType="#//StsGenClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StsGenFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notUsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shared" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="false"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//StsGenClass"
        eOpposite="#//StsGenClass/genFeatures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="ID" value="1"/>
    <eLiterals name="ADJECTIVE_BEFORE" value="2" literal="Adjective before"/>
    <eLiterals name="ADJECTIVE_AFTER" value="3" literal="Adjective after"/>
    <eLiterals name="ATTRIBUTE" value="4" literal="Attribute"/>
    <eLiterals name="CONTAINER" value="5" literal="Container"/>
    <eLiterals name="REFERENCE" value="6" literal="Reference"/>
  </eClassifiers>
</ecore:EPackage>
